"""esquema completo: 6 tablas desde modelos

Revision ID: de1d87cc0b82
Revises: 0001_baseline
Create Date: 2026-09-20 15:41:22.872354

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de1d87cc0b82"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GruposPadres",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("Nombre", sa.String(length=50), nullable=False),
        sa.Column("Descripcion", sa.String(length=200), nullable=True),
        sa.Column("Orden", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint("Nombre"),
    )
    op.create_table(
        "Usuarios",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("Email", sa.String(length=255), nullable=False),
        sa.Column("PasswordHash", sa.String(), nullable=True),
        sa.Column("DisplayName", sa.String(length=255), nullable=False),
        sa.Column("Notas", sa.Text(), nullable=True),
        sa.Column("Especialidad", sa.Text(), nullable=True),
        sa.Column("Role", sa.String(length=50), nullable=False),
        sa.Column("EstadoActual", sa.String(length=20), nullable=False),
        sa.Column("CanViewDashboard", sa.Boolean(), nullable=False),
        sa.Column("CreatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UpdatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint("Email"),
    )
    op.create_table(
        "Grupos",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("GrupoPadreId", sa.Integer(), nullable=False),
        sa.Column("Nombre", sa.String(length=100), nullable=False),
        sa.Column("Activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["GrupoPadreId"],
            ["GruposPadres.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint("GrupoPadreId", "Nombre"),
    )
    op.create_table(
        "Horarios",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("UsuarioId", sa.Integer(), nullable=False),
        sa.Column("Label", sa.String(length=100), nullable=False),
        sa.Column("HoraInicio1", sa.String(length=5), nullable=True),
        sa.Column("HoraFin1", sa.String(length=5), nullable=True),
        sa.Column("HoraInicio2", sa.String(length=5), nullable=True),
        sa.Column("HoraFin2", sa.String(length=5), nullable=True),
        sa.Column("Mes", sa.Integer(), nullable=False),
        sa.Column("Anio", sa.Integer(), nullable=False),
        sa.Column("CreatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["UsuarioId"],
            ["Usuarios.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint("UsuarioId", "Mes", "Anio"),
    )
    op.create_table(
        "Areas",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("GrupoPadreId", sa.Integer(), nullable=False),
        sa.Column("GrupoId", sa.Integer(), nullable=True),
        sa.Column("Nombre", sa.String(length=200), nullable=False),
        sa.Column("Activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["GrupoId"],
            ["Grupos.Id"],
        ),
        sa.ForeignKeyConstraint(
            ["GrupoPadreId"],
            ["GruposPadres.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint("GrupoPadreId", "GrupoId", "Nombre"),
    )
    op.create_table(
        "Atenciones",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("UsuarioId", sa.Integer(), nullable=False),
        sa.Column("GrupoPadreId", sa.Integer(), nullable=True),
        sa.Column("GrupoId", sa.Integer(), nullable=True),
        sa.Column("AreaId", sa.Integer(), nullable=True),
        sa.Column("AreaSolicitante", sa.String(length=200), nullable=False),
        sa.Column("MedioSolicitud", sa.String(length=50), nullable=False),
        sa.Column("UsuarioSolicitante", sa.String(length=10), nullable=False),
        sa.Column("Categoria", sa.String(length=200), nullable=False),
        sa.Column("Descripcion", sa.String(length=1000), nullable=False),
        sa.Column("Solucion", sa.String(length=1000), nullable=False),
        sa.Column("Observaciones", sa.String(length=2000), nullable=True),
        sa.Column("EnlaceApoyo", sa.String(length=500), nullable=True),
        sa.Column("ColaboradorId", sa.Integer(), nullable=True),
        sa.Column("FueraDeTurno", sa.Boolean(), nullable=False),
        sa.Column("FechaRegistro", sa.Date(), nullable=False),
        sa.Column("CreatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["AreaId"],
            ["Areas.Id"],
        ),
        sa.ForeignKeyConstraint(
            ["ColaboradorId"],
            ["Usuarios.Id"],
        ),
        sa.ForeignKeyConstraint(
            ["GrupoId"],
            ["Grupos.Id"],
        ),
        sa.ForeignKeyConstraint(
            ["GrupoPadreId"],
            ["GruposPadres.Id"],
        ),
        sa.ForeignKeyConstraint(
            ["UsuarioId"],
            ["Usuarios.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
    )
    op.create_index("IX_Atenciones_AreaId", "Atenciones", ["AreaId"], unique=False)
    op.create_index(
        "IX_Atenciones_ColaboradorId", "Atenciones", ["ColaboradorId"], unique=False
    )
    op.create_index(
        "IX_Atenciones_FechaRegistro", "Atenciones", ["FechaRegistro"], unique=False
    )
    op.create_index("IX_Atenciones_GrupoId", "Atenciones", ["GrupoId"], unique=False)
    op.create_index(
        "IX_Atenciones_GrupoPadreId", "Atenciones", ["GrupoPadreId"], unique=False
    )
    op.create_index(
        "IX_Atenciones_UsuarioId", "Atenciones", ["UsuarioId"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IX_Atenciones_UsuarioId", table_name="Atenciones")
    op.drop_index("IX_Atenciones_GrupoPadreId", table_name="Atenciones")
    op.drop_index("IX_Atenciones_GrupoId", table_name="Atenciones")
    op.drop_index("IX_Atenciones_FechaRegistro", table_name="Atenciones")
    op.drop_index("IX_Atenciones_ColaboradorId", table_name="Atenciones")
    op.drop_index("IX_Atenciones_AreaId", table_name="Atenciones")
    op.drop_table("Atenciones")
    op.drop_table("Areas")
    op.drop_table("Horarios")
    op.drop_table("Grupos")
    op.drop_table("Usuarios")
    op.drop_table("GruposPadres")
    # ### end Alembic commands ###
